const translations={
ja:{
"nav.about":"会社案内","nav.services":"事業内容","nav.strengths":"強み","nav.message":"代表メッセージ","nav.contact":"お問い合わせ",
"hero.eyebrow":"DEMOLITION · CONSTRUCTION · MANAGEMENT","hero.title":"安全を基盤に、<br><em>確かな未来を築く。</em>","hero.text":"Golden Stone株式会社は、解体工事、建設工事、廃棄物管理を通じて、安全性・品質・責任を重視したサービスを提供します。","hero.cta":"お問い合わせ","hero.secondary":"事業内容を見る",
"stats.years":"年の経験","stats.projects":"大小の施工実績","stats.network":"日本・モンゴル対応",
"about.tag":"ABOUT US","about.title":"信頼される仕事を、<br>一つひとつ確実に。","about.p1":"Golden Stone株式会社は、「安全・信頼・責任」を大切にし、解体・建設・廃棄物管理の各分野で専門性を高めてきました。","about.p2":"現場ごとの条件を丁寧に把握し、施工計画から安全管理、工程管理、整理・搬出まで、プロジェクト全体を見据えた対応を行います。",
"values.safety.title":"安全","values.safety.text":"すべての業務において安全を最優先に考えます。","values.trust.title":"信頼","values.trust.text":"長期的な信頼関係につながる誠実な仕事を徹底します。","values.responsibility.title":"責任","values.responsibility.text":"品質・工程・約束に責任を持ち、最後までやり遂げます。",
"services.tag":"SERVICES","services.title":"事業内容","services.intro":"大型案件から小規模工事まで、現場条件に合わせた最適な施工方法を提案します。","services.demolition.title":"解体工事","services.demolition.text":"鉄筋コンクリート建物、基礎、地下構造物などの解体に対応。分別・積込・搬出まで一体的に管理します。","services.construction.title":"建設工事","services.construction.text":"安全・品質・工程を重視し、現場に適した施工体制で建設関連工事を実施します。","services.waste.title":"廃棄物管理","services.waste.text":"解体材・金属・コンクリート等の適切な分別と搬出を通じ、環境負荷低減を目指します。","services.equipment.title":"重機施工・現場管理","services.equipment.text":"重機を活用した施工、現場内運搬、安全管理、工程管理を含めた総合的な現場運営に対応します。",
"strengths.tag":"WHY GOLDEN STONE","strengths.title":"選ばれる理由","strengths.visual":"SAFETY FIRST · PROFESSIONAL EXECUTION","strengths.s1.title":"安全を最優先","strengths.s1.text":"作業前計画、危険予知、現場管理を重視し、安全な施工を徹底します。","strengths.s2.title":"豊富な現場経験","strengths.s2.text":"7年以上、120件を超える大小の案件を通じて蓄積した実務経験があります。","strengths.s3.title":"一貫した対応","strengths.s3.text":"解体、分別、積込、搬出、整地まで現場全体を見据えて管理します。","strengths.s4.title":"日本・モンゴルのネットワーク","strengths.s4.text":"国境を越えた相談や連携にも柔軟に対応できる体制を整えています。",
"message.tag":"MESSAGE","message.title":"代表メッセージ","message.lead":"「安全・信頼・責任」を軸に、未来へつながる仕事を。","message.p1":"私たちは、どのような現場においても安全がすべての基盤であると考えています。高い施工品質、専門性、そしてお客様との約束を守る責任感が、長期的な信頼につながります。","message.p2":"また、これからの建設・解体業には、品質だけでなく環境への配慮、資源の有効活用、適切な廃棄物処理が欠かせません。Golden Stoneは、より良い現場づくりと持続可能な社会への貢献を目指し、進化を続けます。","message.role":"代表取締役","message.name":"Chuluunbat Enkhbat",
"company.tag":"COMPANY","company.title":"会社概要","company.nameLabel":"会社名","company.establishedLabel":"設立","company.established":"2019年7月19日","company.addressLabel":"所在地","company.address":"〒121-0801 東京都足立区東伊興2丁目1番2号 ブランピア101","company.businessLabel":"主要事業","company.business":"解体工事・建設工事・廃棄物管理・重機施工",
"contact.tag":"CONTACT","contact.title":"ご相談・お見積りは<br>お気軽にお問い合わせください。","contact.text":"解体工事、建設工事、現場管理、重機施工など、案件の規模を問わずご相談ください。","contact.addressLabel":"Address","contact.address":"東京都足立区東伊興2丁目1番2号 ブランピア101","footer.rights":"All Rights Reserved.","footer.top":"Back to top ↑"},
en:{
"nav.about":"About","nav.services":"Services","nav.strengths":"Why Us","nav.message":"Message","nav.contact":"Contact",
"hero.eyebrow":"DEMOLITION · CONSTRUCTION · MANAGEMENT","hero.title":"Safety first.<br><em>Building a stronger future.</em>","hero.text":"Golden Stone Co., Ltd. provides professional demolition, construction and waste-management services with a strong focus on safety, quality and responsibility.","hero.cta":"Contact Us","hero.secondary":"Explore Services",
"stats.years":"Years of experience","stats.projects":"Projects completed","stats.network":"Japan & Mongolia network",
"about.tag":"ABOUT US","about.title":"Reliable work.<br>Delivered with precision.","about.p1":"Golden Stone Co., Ltd. is built on three core values: Safety, Trust and Responsibility. We continue to strengthen our expertise across demolition, construction and waste management.","about.p2":"We assess each site carefully and manage the full project lifecycle — from work planning and safety control to scheduling, sorting, loading and removal.",
"values.safety.title":"Safety","values.safety.text":"Safety is the highest priority in every operation we undertake.","values.trust.title":"Trust","values.trust.text":"We work with integrity to build relationships that last.","values.responsibility.title":"Responsibility","values.responsibility.text":"We take full responsibility for quality, schedules and commitments.",
"services.tag":"SERVICES","services.title":"What We Do","services.intro":"From large-scale projects to smaller jobs, we propose the right execution method for each site condition.","services.demolition.title":"Demolition","services.demolition.text":"Demolition of reinforced-concrete buildings, foundations and underground structures, with integrated sorting, loading and removal management.","services.construction.title":"Construction","services.construction.text":"Construction-related work delivered through site-specific teams with rigorous safety, quality and schedule control.","services.waste.title":"Waste Management","services.waste.text":"Responsible sorting and removal of concrete, metal and demolition materials with a focus on reducing environmental impact.","services.equipment.title":"Heavy Equipment & Site Management","services.equipment.text":"Integrated site operations including heavy equipment work, internal transport, safety control and schedule management.",
"strengths.tag":"WHY GOLDEN STONE","strengths.title":"Why Clients Choose Us","strengths.visual":"SAFETY FIRST · PROFESSIONAL EXECUTION","strengths.s1.title":"Safety First","strengths.s1.text":"We emphasize pre-work planning, risk awareness and disciplined site management.","strengths.s2.title":"Proven Experience","strengths.s2.text":"More than 7 years of practical experience across over 120 projects of various sizes.","strengths.s3.title":"End-to-End Execution","strengths.s3.text":"We manage demolition, sorting, loading, removal and final site preparation as one coordinated process.","strengths.s4.title":"Japan–Mongolia Network","strengths.s4.text":"Our cross-border network enables flexible communication and project coordination between Japan and Mongolia.",
"message.tag":"MESSAGE","message.title":"Message from the Director","message.lead":"Safety, Trust and Responsibility — the foundation of every project.","message.p1":"We believe safety is the foundation of every successful project. High-quality execution, professional expertise and responsibility toward our clients are what create lasting trust.","message.p2":"Today, construction and demolition must go beyond quality alone. Environmental responsibility, efficient use of resources and proper waste handling are equally important. Golden Stone will continue to evolve, creating better worksites and contributing to a more sustainable future.","message.role":"Representative Director","message.name":"Chuluunbat Enkhbat",
"company.tag":"COMPANY","company.title":"Company Profile","company.nameLabel":"Company","company.establishedLabel":"Established","company.established":"July 19, 2019","company.addressLabel":"Head Office","company.address":"Blancpia 101, 2-1-2 Higashi-Iko, Adachi-ku, Tokyo 121-0801, Japan","company.businessLabel":"Core Business","company.business":"Demolition, Construction, Waste Management, Heavy Equipment Operations",
"contact.tag":"CONTACT","contact.title":"Talk to us about<br>your next project.","contact.text":"Contact us for demolition, construction, site management or heavy-equipment work — regardless of project size.","contact.addressLabel":"Address","contact.address":"Blancpia 101, 2-1-2 Higashi-Iko, Adachi-ku, Tokyo 121-0801, Japan","footer.rights":"All Rights Reserved.","footer.top":"Back to top ↑"}}
;
function setLanguage(lang){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(translations[lang][key]!==undefined)el.innerHTML=translations[lang][key]});document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('gs-lang',lang)}
document.querySelectorAll('.lang-btn').forEach(btn=>btn.addEventListener('click',()=>setLanguage(btn.dataset.lang)));
const menuBtn=document.querySelector('.menu-btn'),mobileMenu=document.querySelector('.mobile-menu');menuBtn.addEventListener('click',()=>{const open=menuBtn.getAttribute('aria-expanded')==='true';menuBtn.setAttribute('aria-expanded',String(!open));mobileMenu.hidden=open});mobileMenu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.hidden=true;menuBtn.setAttribute('aria-expanded','false')}));document.getElementById('year').textContent=new Date().getFullYear();setLanguage(localStorage.getItem('gs-lang')||'ja');
